### PR TITLE
Bring API docs in line with real API

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
In addition to erikras/final-form#8

Also made some small changes to the `flow` typings to be in line also.

### CODE REVIEW

**Comment by circlingthesun** [comment]
In the FormRenderProps 'validating' (as seen here: https://codesandbox.io/s/wy7z7q5zx5) is also undocumented.

**Comment by MichaelDeBoey** [comment]
@circlingthesun I only added the changed I made for erikras/final-form#8, but will check the flow types and update the API docs accordingly 🙂

**Comment by MichaelDeBoey** [comment]
> This object contains everything in [🏁 Final Form's `FormState`](https://github.com/erikras/final-form#formstate) as well as:

@circlingthesun The docs for `FormRenderProps` are clear imo, but the `flow` type needs to be adjusted 🙂

**Comment by MichaelDeBoey** [comment]
@erikras It's best to run `prettier` once again I think 🙂

**Pull request merged**
